title: X
author: X
subtitle: A minimal jekyll theme

url: "https://xinkai-zhou.github.io"
baseurl: "/parchment"

footer_only_homepage: true
footer_url: ""
footer_text: "Theme by pro-panda"

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
#  - name: "Resume"
#    absolute-link: "https://pro-panda.github.io/resume.pdf"
